#!/bin/sh
#
cd edi
topno=`ls ip/sent | sort -n | tail -1`
#echo pre $topno
topno=`expr $topno + 1`
#echo TOPNO is $topno
mkdir ip/sent/$topno
mv [0-9][0-9][0-9][0-9]*.dat ip/sent/$topno
#test $? -ne 0 && echo Nothing to send && exit 1
sleep 10  ## to allow invoice to complete
cd ip/sent/$topno
sz *.dat
#tar -cvf /dev/fd1135ds18 .
test $? -eq 0 && echo Success && exit 0
echo FAILED TO SEND BATCH $topno
exit 2

