#define CL_stt    1
#define CL_UNIQ   1
#define CL_PRT    2
#define CL_SI     3
#define CL_SUP    4
#define CL_CUST   5
#define CL_INV    6
#define CL_SALE   7
#define CL_PMT    8
#define CL_ACC    9
#define CL_AGNT  10
#define CL_EXP   11
#define CL_TAKE  12
#define CL_BANK  13
#define CL_ROUND 14
#define CL_SR    15
#define CL_TRANCHE 16
#define CL_TT_REG 17
#define CL_end    17

#define IX_stt    1
#define IX_PRT    1
#define IX_SUP    2
#define IX_SUPDCN 3
#define IX_CUST   4
#define IX_CUSTSN 5
#define IX_STK    6
#define IX_STKLN  7
#define IX_STKBC  8
#define IX_SR     9
#define IX_AGNT   10
#define IX_AGNTNM 11
#define IX_SALE   12
#define IX_INV    13
#define IX_PMT    14
#define IX_EXP    15
#define IX_CACC   16
#define IX_ROUND  17
#define IX_TAKE   18
#define IX_BANK   19
#define IX_TCHE   20
#define IX_BACC   21
#define IX_MANBC  22
#define IX_TT     23
#define IX_end    23

#define ADMIN_AGT     1
#define BANK_AGT     (-1)
#define INTEREST_AGT (-2)
